appiumDriver = http://127.0.0.1:4723
platformName = Android
automationName = uiautomator2
deviceName = Pixel_8a_API_36
platformVersion = 16
app = app/googleCalculator.apk
appPackage = com.google.android.calculator
appActivity = com.android.calculator2.Calculator